/**
 * Model capabilities used for hard routing constraints.
 *
 * Hosts may inject fresher values through RouterOptions.modelCapabilities.
 * Keeping a small built-in snapshot makes the core safe and useful when a
 * product catalog is temporarily unavailable, without importing product code.
 *
 * GENERATED by scripts/sync-model-capabilities.mjs from the public catalog
 * (GET https://blockrun.ai/api/v1/models) on 2026-08-31; supportsTools comes
 * from a live function-calling probe (scripts/probe-tools.json). Regenerate
 * rather than editing by hand — a hand edit is overwritten on the next sync.
 */
export type ModelCapabilities = {
  contextWindow: number;
  maxOutputTokens: number;
  supportsTools: boolean;
  supportsVision: boolean;
};

export const DEFAULT_MODEL_CAPABILITIES: Readonly<Record<string, ModelCapabilities>> =
  Object.freeze({
    "anthropic/claude-fable-5": {
      contextWindow: 1_000_000,
      maxOutputTokens: 128_000,
      supportsTools: true,
      supportsVision: true,
    },
    "anthropic/claude-haiku-4.5": { // override: The public catalog's `categories` omit "vision" for this Anthropic model even though the gateway accepts image input for it (the prior hand-maintained snapshot had it, and Anthropic's model card lists it). Without this the vision filter would silently drop it — reported against the catalog; remove once the categories carry vision.
      contextWindow: 200_000,
      maxOutputTokens: 64_000,
      supportsTools: true,
      supportsVision: true,
    },
    "anthropic/claude-opus-4.5": {
      contextWindow: 200_000,
      maxOutputTokens: 64_000,
      supportsTools: true,
      supportsVision: true,
    },
    "anthropic/claude-opus-4.7": {
      contextWindow: 1_000_000,
      maxOutputTokens: 128_000,
      supportsTools: true,
      supportsVision: true,
    },
    "anthropic/claude-opus-4.8": {
      contextWindow: 1_000_000,
      maxOutputTokens: 128_000,
      supportsTools: true,
      supportsVision: true,
    },
    "anthropic/claude-opus-5": {
      contextWindow: 1_000_000,
      maxOutputTokens: 128_000,
      supportsTools: true,
      supportsVision: true,
    },
    "anthropic/claude-sonnet-4.5": {
      contextWindow: 200_000,
      maxOutputTokens: 64_000,
      supportsTools: true,
      supportsVision: true,
    },
    "anthropic/claude-sonnet-4.6": { // override: The public catalog's `categories` omit "vision" for this Anthropic model even though the gateway accepts image input for it (the prior hand-maintained snapshot had it, and Anthropic's model card lists it). Without this the vision filter would silently drop it — reported against the catalog; remove once the categories carry vision.
      contextWindow: 1_000_000,
      maxOutputTokens: 128_000,
      supportsTools: true,
      supportsVision: true,
    },
    "anthropic/claude-sonnet-5": {
      contextWindow: 1_000_000,
      maxOutputTokens: 128_000,
      supportsTools: true,
      supportsVision: true,
    },
    "cohere/north-mini-code": { // supportsTools: not probed — fails closed
      contextWindow: 256_000,
      maxOutputTokens: 16_384,
      supportsTools: false,
      supportsVision: false,
    },
    "deepseek/deepseek-chat": {
      contextWindow: 1_048_576,
      maxOutputTokens: 65_536,
      supportsTools: true,
      supportsVision: false,
    },
    "deepseek/deepseek-reasoner": {
      contextWindow: 1_048_576,
      maxOutputTokens: 65_536,
      supportsTools: true,
      supportsVision: false,
    },
    "deepseek/deepseek-v4-pro": {
      contextWindow: 1_048_576,
      maxOutputTokens: 65_536,
      supportsTools: true,
      supportsVision: false,
    },
    "google/gemini-2.5-flash": {
      contextWindow: 1_048_576,
      maxOutputTokens: 65_536,
      supportsTools: true,
      supportsVision: true,
    },
    "google/gemini-2.5-flash-lite": {
      contextWindow: 1_048_576,
      maxOutputTokens: 65_536,
      supportsTools: true,
      supportsVision: false,
    },
    "google/gemini-2.5-pro": {
      contextWindow: 1_048_576,
      maxOutputTokens: 65_536,
      supportsTools: true,
      supportsVision: true,
    },
    "google/gemini-3-flash-preview": {
      contextWindow: 1_048_576,
      maxOutputTokens: 65_536,
      supportsTools: true,
      supportsVision: true,
    },
    "google/gemini-3.1-flash-lite": {
      contextWindow: 1_048_576,
      maxOutputTokens: 65_536,
      supportsTools: true,
      supportsVision: false,
    },
    "google/gemini-3.1-pro": {
      contextWindow: 1_048_576,
      maxOutputTokens: 65_536,
      supportsTools: true,
      supportsVision: true,
    },
    "google/gemini-3.5-flash": {
      contextWindow: 1_048_576,
      maxOutputTokens: 65_536,
      supportsTools: true,
      supportsVision: true,
    },
    "google/gemini-3.5-flash-lite": {
      contextWindow: 1_048_576,
      maxOutputTokens: 65_536,
      supportsTools: true,
      supportsVision: false,
    },
    "google/gemini-3.6-flash": {
      contextWindow: 1_048_576,
      maxOutputTokens: 65_536,
      supportsTools: true,
      supportsVision: true,
    },
    "minimax/minimax-m2.7": {
      contextWindow: 204_800,
      maxOutputTokens: 16_384,
      supportsTools: true,
      supportsVision: false,
    },
    "minimax/minimax-m3": {
      contextWindow: 1_048_576,
      maxOutputTokens: 65_536,
      supportsTools: true,
      supportsVision: false,
    },
    "moonshot/kimi-k3": {
      contextWindow: 1_048_576,
      maxOutputTokens: 65_536,
      supportsTools: true,
      supportsVision: true,
    },
    "nvidia/llama-3.2-11b-vision": { // supportsTools: not probed — fails closed
      contextWindow: 128_000,
      maxOutputTokens: 16_384,
      supportsTools: false,
      supportsVision: true,
    },
    "nvidia/nemotron-3-nano-30b": { // supportsTools: not probed — fails closed
      contextWindow: 131_072,
      maxOutputTokens: 16_384,
      supportsTools: false,
      supportsVision: false,
    },
    "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning": {
      contextWindow: 256_000,
      maxOutputTokens: 16_384,
      supportsTools: false,
      supportsVision: true,
    },
    "nvidia/nemotron-3-ultra-550b": { // supportsTools: not probed — fails closed
      contextWindow: 1_000_000,
      maxOutputTokens: 16_384,
      supportsTools: false,
      supportsVision: false,
    },
    "nvidia/nemotron-3.5-lightning": { // supportsTools: not probed — fails closed
      contextWindow: 1_000_000,
      maxOutputTokens: 16_384,
      supportsTools: false,
      supportsVision: false,
    },
    "openai/chat-latest": {
      contextWindow: 128_000,
      maxOutputTokens: 128_000,
      supportsTools: true,
      supportsVision: true,
    },
    "openai/gpt-4.1": {
      contextWindow: 128_000,
      maxOutputTokens: 32_768,
      supportsTools: true,
      supportsVision: true,
    },
    "openai/gpt-4.1-mini": {
      contextWindow: 128_000,
      maxOutputTokens: 32_768,
      supportsTools: true,
      supportsVision: false,
    },
    "openai/gpt-4.1-nano": {
      contextWindow: 128_000,
      maxOutputTokens: 32_768,
      supportsTools: true,
      supportsVision: false,
    },
    "openai/gpt-4o": {
      contextWindow: 128_000,
      maxOutputTokens: 16_384,
      supportsTools: true,
      supportsVision: true,
    },
    "openai/gpt-4o-mini": {
      contextWindow: 128_000,
      maxOutputTokens: 16_384,
      supportsTools: true,
      supportsVision: false,
    },
    "openai/gpt-5-mini": {
      contextWindow: 200_000,
      maxOutputTokens: 128_000,
      supportsTools: true,
      supportsVision: false,
    },
    "openai/gpt-5.2": {
      contextWindow: 400_000,
      maxOutputTokens: 128_000,
      supportsTools: true,
      supportsVision: true,
    },
    "openai/gpt-5.2-pro": { // supportsTools: not probed — fails closed
      contextWindow: 400_000,
      maxOutputTokens: 128_000,
      supportsTools: false,
      supportsVision: true,
    },
    "openai/gpt-5.3-codex": { // supportsTools: gateway unavailable at probe time — fails closed; override: 2026-08-29 probe: every request (6 plain + 3 tool attempts) returned a gateway 500, so the probe measured an incident, not the model. Codex's function calling is established by the 2026-07 Terminal-Bench / tau2 calibration trajectories in portfolio.ts. Hosts observing the 500s should drop it with RouterOptions.unavailableModels rather than this snapshot claiming the model cannot call tools.
      contextWindow: 400_000,
      maxOutputTokens: 128_000,
      supportsTools: true,
      supportsVision: false,
    },
    "openai/gpt-5.4": {
      contextWindow: 1_050_000,
      maxOutputTokens: 128_000,
      supportsTools: true,
      supportsVision: true,
    },
    "openai/gpt-5.4-mini": {
      contextWindow: 400_000,
      maxOutputTokens: 128_000,
      supportsTools: true,
      supportsVision: true,
    },
    "openai/gpt-5.4-nano": {
      contextWindow: 1_050_000,
      maxOutputTokens: 128_000,
      supportsTools: true,
      supportsVision: false,
    },
    "openai/gpt-5.4-pro": { // supportsTools: not probed — fails closed
      contextWindow: 1_050_000,
      maxOutputTokens: 128_000,
      supportsTools: false,
      supportsVision: true,
    },
    "openai/gpt-5.5": {
      contextWindow: 1_050_000,
      maxOutputTokens: 128_000,
      supportsTools: true,
      supportsVision: true,
    },
    "openai/gpt-5.5-pro": { // supportsTools: not probed — fails closed
      contextWindow: 1_050_000,
      maxOutputTokens: 128_000,
      supportsTools: false,
      supportsVision: true,
    },
    "openai/gpt-5.6-luna": {
      contextWindow: 1_050_000,
      maxOutputTokens: 128_000,
      supportsTools: true,
      supportsVision: true,
    },
    "openai/gpt-5.6-luna-pro": {
      contextWindow: 1_050_000,
      maxOutputTokens: 128_000,
      supportsTools: false,
      supportsVision: true,
    },
    "openai/gpt-5.6-sol": {
      contextWindow: 1_050_000,
      maxOutputTokens: 128_000,
      supportsTools: true,
      supportsVision: true,
    },
    "openai/gpt-5.6-sol-pro": {
      contextWindow: 1_050_000,
      maxOutputTokens: 128_000,
      supportsTools: true,
      supportsVision: true,
    },
    "openai/gpt-5.6-terra": {
      contextWindow: 1_050_000,
      maxOutputTokens: 128_000,
      supportsTools: true,
      supportsVision: true,
    },
    "openai/gpt-5.6-terra-pro": {
      contextWindow: 1_050_000,
      maxOutputTokens: 128_000,
      supportsTools: true,
      supportsVision: true,
    },
    "openai/o1": {
      contextWindow: 200_000,
      maxOutputTokens: 100_000,
      supportsTools: true,
      supportsVision: false,
    },
    "openai/o3": {
      contextWindow: 200_000,
      maxOutputTokens: 100_000,
      supportsTools: true,
      supportsVision: false,
    },
    "openai/o3-mini": {
      contextWindow: 128_000,
      maxOutputTokens: 100_000,
      supportsTools: true,
      supportsVision: false,
    },
    "openai/o4-mini": {
      contextWindow: 128_000,
      maxOutputTokens: 100_000,
      supportsTools: true,
      supportsVision: false,
    },
    "poolside/laguna-xs-2.1": { // supportsTools: not probed — fails closed
      contextWindow: 131_072,
      maxOutputTokens: 16_384,
      supportsTools: false,
      supportsVision: false,
    },
    "qwen/qwen3.7-flash": {
      contextWindow: 1_000_000,
      maxOutputTokens: 65_536,
      supportsTools: true,
      supportsVision: false,
    },
    "qwen/qwen3.7-max": {
      contextWindow: 1_000_000,
      maxOutputTokens: 65_536,
      supportsTools: true,
      supportsVision: false,
    },
    "qwen/qwen3.7-plus": {
      contextWindow: 1_000_000,
      maxOutputTokens: 131_072,
      supportsTools: true,
      supportsVision: false,
    },
    "tencent/hy3": {
      contextWindow: 262_144,
      maxOutputTokens: 128_000,
      supportsTools: true,
      supportsVision: false,
    },
    "xai/grok-4.3": {
      contextWindow: 1_000_000,
      maxOutputTokens: 16_384,
      supportsTools: true,
      supportsVision: true,
    },
    "xai/grok-4.5": {
      contextWindow: 500_000,
      maxOutputTokens: 16_384,
      supportsTools: true,
      supportsVision: true,
    },
    "xai/grok-build-0.1": {
      contextWindow: 256_000,
      maxOutputTokens: 16_384,
      supportsTools: true,
      supportsVision: false,
    },
    "xiaomi/mimo-v2.5-pro": {
      contextWindow: 1_048_576,
      maxOutputTokens: 131_072,
      supportsTools: true,
      supportsVision: false,
    },
    "zai/glm-5": {
      contextWindow: 200_000,
      maxOutputTokens: 128_000,
      supportsTools: true,
      supportsVision: false,
    },
    "zai/glm-5-turbo": {
      contextWindow: 200_000,
      maxOutputTokens: 128_000,
      supportsTools: true,
      supportsVision: false,
    },
    "zai/glm-5.1": {
      contextWindow: 200_000,
      maxOutputTokens: 128_000,
      supportsTools: true,
      supportsVision: false,
    },
    "zai/glm-5.2": {
      contextWindow: 1_000_000,
      maxOutputTokens: 131_072,
      supportsTools: true,
      supportsVision: false,
    },
    "zai/glm-5.3": {
      contextWindow: 1_000_000,
      maxOutputTokens: 131_072,
      supportsTools: true,
      supportsVision: false,
    },
    "zai/glm-5.3-flash": {
      contextWindow: 1_000_000,
      maxOutputTokens: 131_072,
      supportsTools: true,
      supportsVision: true,
    },
  });
